# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-12-20 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age_letter',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='unknown', max_length=48),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], max_length=48),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'extra large'), ('u', 'unknown')], default='unknown', max_length=48),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(default='b,y,a,s', max_length=7),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(default='m,f', max_length=3),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(default='s,m,l,xl', max_length=8),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prefs', to=settings.AUTH_USER_MODEL),
        ),
    ]
