# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-12-20 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0003_dog_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age_letter',
            field=models.CharField(editable=False, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
