# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2020-01-02 18:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0004_auto_20191220_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='joined',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 1, 2, 18, 37, 20, 385066, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
